# Generated by Django 5.0.1 on 2024-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
