# Generated by Django 5.0.2 on 2024-02-19 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clients_update_at_clients_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
